### ISSUE TITLE
Im getting therunpod.error.QueryError error 

### ISSUE THREAD

**Issue by dillaryclump** [runpod/runpod-python#150]
**Describe the bug**
when trying to run : `runpod.create_pod("tortoise", "dillonbishop/ai-tts:latest", "NVIDIA GeForce RTX 3070",docker_args="bash -c 'apt update;DEBIAN_FRONTEND=noninteractive apt-get install openssh-server -y;mkdir -p ~/.ssh;cd $_;chmod 700 ~/.ssh;echo \"$PUBLIC_KEY\" >> authorized_keys;chmod 700 authorized_keys;service ssh start;docker pull dillonbishop/ai-tts:latest'")`

im getting this error: 

runpod.error.QueryError: Something went wrong. Please try again later or contact support.

heres the full trace back:
Traceback (most recent call last):
  File "D:\PycharmProjects\aibigcontentcreation\main.py", line 599, in <module>
    wholething()
  File "D:\PycharmProjects\aibigcontentcreation\main.py", line 578, in wholething
    runpod.create_pod("tortoise", "dillonbishop/ai-tts:latest", "NVIDIA GeForce RTX 3070",docker_args="bash -c 'apt update;DEBIAN_FRONTEND=noninteractive apt-get install openssh-server -y;mkdir -p ~/.ssh;cd $_;chmod 700 ~/.ssh;echo \"$PUBLIC_KEY\" >> authorized_keys;chmod 700 authorized_keys;service ssh start;docker pull dillonbishop/ai-tts:latest'")
  File "C:\Users\Dillon's PC\AppData\Local\Programs\Python\Python310\lib\site-packages\runpod\api\ctl_commands.py", line 92, in create_pod
    raw_response = run_graphql_query(
  File "C:\Users\Dillon's PC\AppData\Local\Programs\Python\Python310\lib\site-packages\runpod\api\graphql.py", line 30, in run_graphql_query
    raise error.QueryError(response.json()["errors"][0]["message"])
runpod.error.QueryError: Something went wrong. Please try again later or contact support.

**Comment by justinmerrell** [comment]
A couple of things:

- No need to include the `docker pull`
- You can also simplify things by including your public SSH key under your account settings; we will inject it automatically into your pod. 
- There is probably an issue with the escaped double quotes, which would be resolved with the point above.

**Comment by dillaryclump** [comment]
hello Im still having trouble with this ive tried several versions of trying to include the ssh-key but every thing doesnt work when I try to put the ssh key inside of this `        runpod.create_pod("tortoise", "thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest", "NVIDIA GeForce RTX 3070",docker_args = '''bash -c 'apt update; DEBIAN_FRONTEND=noninteractive apt-get install openssh-server -y; mkdir -p ~/.ssh; echo "$PUBLIC_KEY" >> ~/.ssh/authorized_keys; chmod 700 ~/.ssh; chmod 600 ~/.ssh/authorized_keys; service ssh start; sleep infinity' ''', ports="22",support_public_ip=True)
` it gives me this error: Traceback (most recent call last):
  File "D:\PycharmProjects\aibigcontentcreation\main.py", line 658, in <module>
    wholething()
  File "D:\PycharmProjects\aibigcontentcreation\main.py", line 636, in wholething
    runpod.create_pod("tortoise", "thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest", "NVIDIA GeForce RTX 3070",docker_args = '''bash -c 'apt update; DEBIAN_FRONTEND=noninteractive apt-get install openssh-server -y; mkdir -p ~/.ssh; echo "$PUBLIC_KEY" >> ~/.ssh/authorized_keys; chmod 700 ~/.ssh; chmod 600 ~/.ssh/authorized_keys; service ssh start; sleep infinity' ''', ports="22",support_public_ip=True)
  File "C:\Users\Dillon's PC\AppData\Local\Programs\Python\Python310\lib\site-packages\runpod\api\ctl_commands.py", line 92, in create_pod
    raw_response = run_graphql_query(
  File "C:\Users\Dillon's PC\AppData\Local\Programs\Python\Python310\lib\site-packages\runpod\api\graphql.py", line 30, in run_graphql_query
    raise error.QueryError(response.json()["errors"][0]["message"])
runpod.error.QueryError: Something went wrong. Please try again later or contact support.

ive tried everything you have said but if I dont include the ssh-key it says it cant find it even though ive added it to my account settings. when it does run it inputs the wrong ssh key and seems to only want to run when the key is wrong. once it has the wrong key it just keeps constantly restarting the server reinstalling the openssh software then starting over.

**Comment by justinmerrell** [comment]
The ports need to be `"22/tcp"`

**Comment by dillaryclump** [comment]
thank you! unfortunately I still cant get this to work

**Comment by dillaryclump** [comment]
no matter what I do I cant seem to be able to dodge this error: Traceback (most recent call last):
  File "D:\PycharmProjects\aibigcontentcreation\main.py", line 668, in <module>
    wholething()
  File "D:\PycharmProjects\aibigcontentcreation\main.py", line 646, in wholething
    runpod.create_pod("tortoise", "ubuntu:latest", "NVIDIA GeForce RTX 3070",docker_args=docker_args, ports="22/tcp", support_public_ip=True)
  File "C:\Users\Dillon's PC\AppData\Local\Programs\Python\Python310\lib\site-packages\runpod\api\ctl_commands.py", line 92, in create_pod
    raw_response = run_graphql_query(
  File "C:\Users\Dillon's PC\AppData\Local\Programs\Python\Python310\lib\site-packages\runpod\api\graphql.py", line 30, in run_graphql_query
    raise error.QueryError(response.json()["errors"][0]["message"])
runpod.error.QueryError: Something went wrong. Please try again later or contact support. I always need to automatically put in the key and yet no matter what I do the graphql wont except it ive even tried with something as stupid as this: 
` with open('setup_script.sh', 'r') as file:
        script_content = file.read()
docker_args = f'''bash -c '{script_content.replace("$PUBLIC_KEY", public_key)}' '''
runpod.create_pod("tortoise", "ubuntu:latest", "NVIDIA GeForce RTX 3070",docker_args=docker_args, ports="22/tcp", support_public_ip=True)
    `

**Comment by havetc** [comment]
Hello!
I'm having the same kind of error while trying to start pods with `runpod.create_pod` or using `runpod.create_container_registry_auth`. Would it be possible to at least have non generic errors returned, to get a better idea of what went wrong? I don't think that can be fixed from the python SDK though :/
