### ISSUE TITLE
Uninformative error message

### ISSUE THREAD

**Issue by LukeWood** [runpod/runpod-python#36]
Thanks for making runpod!  Its great!

I'm getting:

```
import runpod

endpoint = runpod.Endpoint("pixi-inpaint-api")

run_request = endpoint.run_sync(
    {
        "image_url": "https://i.imgur.com/FxcvsYN.png",
        "prompt": "A corgi wearing cool sunglasses",
        "mask_url": "https://i.imgur.com/wl3vekS.png",
    }
)

```
```
➜  test git:(runpod) ✗ python run.py
Initialized endpoint: pixi-inpaint-api
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

and dont know how to debug

**Comment by justinmerrell** [comment]
Where are you getting the name `pixi-inpaint-api`?

**Comment by LukeWood** [comment]
> Where are you getting the name `pixi-inpaint-api`?

That was the name of my endpoint, but I updated it to the runpod UID.  It still didn't work, the solution was assigning `runpod.api_key = `.  Maybe we can check in the SDK if the runpod API key has been provided?

**Comment by justinmerrell** [comment]
Thank you for the PR, reviewing now
